[book]
authors = ["Hervy Qurrotul Ainur Rozi"]
language = "id"
multilingual = false
src = "src"
title = "Wikipedia LangitKetujuh OS"
description = "Panduan dan tutorial menggunakan LangitKetujuh OS"

[build]
build-dir = "wiki"
create-missing = false

[output.html]
theme = "src/theme"
default-theme = "light"
preferred-dark-theme = "coal"
additional-js=["register-sw.js"]
git-repository-url= "https://gitlab.com/langitketujuh/l7-wiki"
edit-url-template = "https://gitlab.com/langitketujuh/l7-wiki/-/blob/master/{path}"
git-repository-icon= "fa-gitlab"
mathjax-support = true
input-404 = "404.md"

[output.html.fold]
enable = false
level = 1

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.linkcheck]
optional = true
